# Generated by Django 4.2 on 2023-04-27 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.TextField()),
                ('description', models.TextField()),
                ('added', models.TextField(blank=True, default='user')),
            ],
            options={
                'db_table': 'Lessons',
            },
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.TextField()),
                ('translate', models.TextField()),
                ('meaning', models.TextField()),
                ('added', models.TextField(blank=True, default='user')),
            ],
            options={
                'db_table': 'Vocabulary',
            },
        ),
    ]
